version: "3.8"
services:
  rates-mock:
    image: wiremock/wiremock:3.7.0
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - "--verbose"
      - "--global-response-templating"
